"""initial schema

Revision ID: 67ab67afaa3c
Revises: 
Create Date: 2025-12-09 21:20:35.223193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67ab67afaa3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('scope_branches', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Map of repository_id -> branch name for query scope'),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('response_citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of citation objects with path, line_start, line_end'),
    sa.Column('response_latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_queries'))
    )
    op.create_index(op.f('ix_queries_user_id'), 'queries', ['user_id'], unique=False)
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('git_url', sa.Text(), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('auth_type', sa.Enum('NONE', 'TOKEN', 'SSH_KEY', 'OAUTH', name='authtype'), nullable=False),
    sa.Column('auth_credential_ref', sa.String(length=512), nullable=True),
    sa.Column('access_state', sa.Enum('PENDING', 'ACTIVE', 'ERROR', 'DISABLED', name='accessstate'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repositories'))
    )
    op.create_index(op.f('ix_repositories_name'), 'repositories', ['name'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('tracked', sa.Boolean(), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_notification_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('freshness_status', sa.Enum('FRESH', 'STALE', 'ERROR', 'PENDING', name='freshnessstatus'), nullable=False),
    sa.Column('backlog_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_branches_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches'))
    )
    op.create_index(op.f('ix_branches_repository_id'), 'branches', ['repository_id'], unique=False)
    op.create_table('query_repositories',
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], name=op.f('fk_query_repositories_query_id_queries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_query_repositories_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('query_id', 'repository_id', name=op.f('pk_query_repositories'))
    )
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.Enum('CODE', 'CONFIG', 'DOC', 'PDF', 'BINARY', 'OTHER', name='filetype'), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('parse_status', sa.Enum('PARSED', 'SKIPPED', 'FAILED', name='parsestatus'), nullable=False),
    sa.Column('has_line_map', sa.Boolean(), nullable=False),
    sa.Column('last_seen_commit', sa.String(length=64), nullable=True),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_artifacts_branch_id_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_artifacts_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts'))
    )
    op.create_index(op.f('ix_artifacts_branch_id'), 'artifacts', ['branch_id'], unique=False)
    op.create_index(op.f('ix_artifacts_repository_id'), 'artifacts', ['repository_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Enum('WEBHOOK', 'SCHEDULE', 'MANUAL', name='notificationsource'), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=True, comment='External event ID from webhook provider'),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'DONE', 'ERROR', name='notificationstatus'), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_notifications_branch_id_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_notifications_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_branch_id'), 'notifications', ['branch_id'], unique=False)
    op.create_index(op.f('ix_notifications_repository_id'), 'notifications', ['repository_id'], unique=False)
    op.create_table('index_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_vector', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name=op.f('fk_index_records_artifact_id_artifacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_index_records_branch_id_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_index_records_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_index_records'))
    )
    op.create_index(op.f('ix_index_records_artifact_id'), 'index_records', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_index_records_branch_id'), 'index_records', ['branch_id'], unique=False)
    op.create_index(op.f('ix_index_records_repository_id'), 'index_records', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_index_records_repository_id'), table_name='index_records')
    op.drop_index(op.f('ix_index_records_branch_id'), table_name='index_records')
    op.drop_index(op.f('ix_index_records_artifact_id'), table_name='index_records')
    op.drop_table('index_records')
    op.drop_index(op.f('ix_notifications_repository_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_branch_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_artifacts_repository_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_branch_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_table('query_repositories')
    op.drop_index(op.f('ix_branches_repository_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_repositories_name'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_queries_user_id'), table_name='queries')
    op.drop_table('queries')
    # ### end Alembic commands ###
